/**
 Helper functions to skip repeating code.
 */
function extractRequirePermits(array) {
  const requirePermits = []
  function traverse(children) {
    children.forEach(child=> {
      if (child.hasOwnProperty('requirePermit') && Array.isArray(child.requirePermit)) {
        requirePermits.push(...child.requirePermit)
      }
      if (child.hasOwnProperty('children') && Array.isArray(child.children)) {
        traverse(child.children)
      }
    })
  }
  traverse(array)

  return requirePermits
}

/**
 main menu items
*/

const KARPOOSHEManagerItems =  [
  {
    title: 'همکاران',
    route: '/KARPOOSHE/basic/employees',
    requirePermit: ['UserList'],
    requirePlugin: [],
    completelyDisable: false,
    lacksPermission: [],
    badgeKey: '',
  },
  {
    title: 'اطلاعات پایه ای',
    badgeKey: '',
    children: [
      {
        title: 'دپارتمان',
        route: '/KARPOOSHE/basic/department',
        requirePermit: ['DepartmentManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'مدیریت دسترسی ها',
        route: '/KARPOOSHE/basic/roles',
        requirePermit: ['RoleManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'پست سازمانی',
        route: '/KARPOOSHE/basic/organization',
        requirePermit: ['OrgPositionalManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
    ],
  },
  {
    title: 'تخصیص به همکار',
    badgeKey: '',
    children: [
      {
        title: 'دسترسی',
        route: '/KARPOOSHE/assign/role',
        requirePermit: ['SetRole'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'دپارتمان',
        route: '/KARPOOSHE/assign/department',
        requirePermit: ['SetDepartment'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'پست سازمانی',
        route: '/KARPOOSHE/assign/orgPosition',
        requirePermit: ['SetOrgPosition'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'تفویض اختیار',
        route: '/KARPOOSHE/assign/delegation',
        requirePermit: ['GrantPermission'],
        requirePlugin: ['GrantPermission'],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'مدیریت اطلاع رسانی',
        route: '/KARPOOSHE/assign/portal-messaging',
        requirePermit: ['NoticeManagment'],
        requirePlugin: ['NoticeManagment'],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
    ],
  },
  {
    title: 'گزارش ها',
    badgeKey: '',
    children: [
      {
        title: 'چارت سازمانی',
        route: '/KARPOOSHE/reports/department-chart',
        requirePermit: ['ShowKarposheReport'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: true,
        badgeKey: '',
      },
    ],
  },
]

const KARPOSHEEmployeeItems = [
  {
    title: 'اطلاعات من',
    badgeKey: '',
    children: [
      {
        title: 'تکمیل اطلاعات',
        route: '/KARPOOSHE/my-profile/complete-info',
        requirePermit:  extractRequirePermits(KARPOOSHEManagerItems),
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'تنظیم اعلان',
        route: '/KARPOOSHE/my-profile/notice-management',
        requirePermit:  extractRequirePermits(KARPOOSHEManagerItems),
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
    ],
  },
  {
    title: 'تکمیل اطلاعات',
    route: '/KARPOOSHE/my-profile/complete-info',
    requirePermit: [],
    requirePlugin: [],
    lacksPermission: extractRequirePermits(KARPOOSHEManagerItems),
    completelyDisable: false,
    badgeKey: '',
  },
  {
    title: 'تنظیم اعلان',
    route: '/KARPOOSHE/my-profile/notice-management',
    requirePermit: [],
    requirePlugin: [],
    lacksPermission: extractRequirePermits(KARPOOSHEManagerItems),
    completelyDisable: false,
    badgeKey: '',
  },
]

const KARSAATManagerItems = [
  {
    title: 'اطلاعات پایه ای',
    badgeKey: '',
    children: [
      {
        title: 'شیفت روزانه',
        route: '/KARSAAT/basic/daily-shift',
        requirePermit: ['ShiftManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'شیفت دوره ای',
        route: '/KARSAAT/basic/rotate-shift',
        requirePermit: ['ShiftManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'شیفت هفتگی',
        route: '/KARSAAT/basic/weekly-shift',
        requirePermit: ['ShiftManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'عدم حضور',
        route: '/KARSAAT/basic/absence',
        requirePermit: ['AbsentManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'ماموریت',
        route: '/KARSAAT/basic/mission',
        requirePermit: ['MissionManagement'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'قوانین کارکرد',
        route: '/KARSAAT/basic/workspace-rules',
        requirePermit: ['WorkspaceRuleManagment'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
    ],
  },
  {
    title: 'تخصیص',
    badgeKey: '',
    children: [
      {
        title: 'عدم حضور',
        route: '/KARSAAT/assign/absent',
        requirePermit: ['SetAbsent'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: 'Absent',
      },
      {
        title: 'تردد',
        route: '/KARSAAT/assign/io',
        requirePermit: ['TimeTrackManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'تردد دسته جمعی',
        route: '/KARSAAT/assign/io-multi',
        requirePermit: ['TimeTrackManager'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      // {
      //   title: 'تایید اضافه کاری',
      //   route: '/KARSAAT/assign/confirm-overtime',
      //   requirePermit: ['CanConfirmOvertime'],
      //   requirePlugin: ['ConfirmOvertime'],
      //   lacksPermission: [],
      //   completelyDisable: true,
      //   badgeKey: '',
      // },
      // {
      //   title: 'بخشش تاخیر یا کسری',
      //   route: '/KARSAAT/assign/shortage-delay-forgive',
      //   requirePermit: ['ForgivenShortageDelay'],
      //   requirePlugin: ['ForgivenDelayOrShortage'],
      //   lacksPermission: [],
      //   completelyDisable: true,
      //   badgeKey: '',
      // },
      {
        title: 'دوره های کارکرد',
        route: '/KARSAAT/assign/work-term',
        requirePermit: ['WorkTermManagment'],
        requirePlugin: ['WorkTerm'],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'شیفت',
        route: '/KARSAAT/assign/shift',
        requirePermit: ['SetShift'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'ماموریت',
        route: '/KARSAAT/assign/mission',
        requirePermit: ['SetMission'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: 'Mission',
      },
      {
        title: 'قوانین کارکرد',
        route: '/KARSAAT/assign/work-rule',
        requirePermit: ['WorkspaceRuleManagment'],
        requirePlugin: ['WorkRule'],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
      {
        title: 'مانده مرخصی',
        route: '/KARSAAT/assign/absent-outcome',
        requirePermit: ['EmployeeAbsentOutcomeManagment'],
        requirePlugin: [],
        lacksPermission: [],
        completelyDisable: false,
        badgeKey: '',
      },
    ],
  },
  {
    title: 'گزارش',
    badgeKey: '',
    children: [
      {
        title: ' تجمیعی همکاران',
        route: '/KARSAAT/report/io-additive',
        requirePermit: ['TimeTrackReportAll'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: 'وضعیت حضور',
        route: '/KARSAAT/report/absent',
        requirePermit: ['PresentReport'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: ' مرخصی همکاران',
        route: '/KARSAAT/report/vacation',
        requirePermit: ['AbsentReports'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: ' نحوه کارکرد',
        route: '/KARSAAT/report/work-type',
        requirePermit: ['IoTypeReport'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: ' شیفت همکاران',
        route: '/KARSAAT/report/shift',
        requirePermit: ['ShiftReport'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: ' تردد همکاران',
        route: '/KARSAAT/report/io',
        requirePermit: ['IoReport'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: 'TemporaryIo',
      },
      {
        title: 'ترددهای تایید نشده',
        route: '/KARSAAT/report/io-pending',
        requirePermit: ['TempIoReport'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: 'حس و حال همکاران',
        route: '/KARSAAT/report/mood-condition',
        requirePermit: ['EmployeMoodCondition'],
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
    ],
  },
]

const KARSAATEmployeeItems = [
  {
    title: 'درخواست های من',
    badgeKey: '',
    children: [
      {
        title: 'مرخصی',
        route: '/KARSAAT/my-request/absent',
        requirePermit: extractRequirePermits(KARSAATManagerItems),
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: 'ماموریت',
        route: '/KARSAAT/my-request/mission',
        requirePermit: extractRequirePermits(KARSAATManagerItems),
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: 'تردد',
        route: '/KARSAAT/my-request/io',
        requirePermit: extractRequirePermits(KARSAATManagerItems),
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: 'شیفت',
        route: '/KARSAAT/my-request/shift',
        requirePermit: extractRequirePermits(KARSAATManagerItems),
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
      {
        title: 'حس و حال',
        route: '/KARSAAT/my-request/mood-condition',
        requirePermit: extractRequirePermits(KARSAATManagerItems),
        requirePlugin: [],
        completelyDisable: false,
        lacksPermission: [],
        badgeKey: '',
      },
    ],
  },
  {
    title: 'مرخصی',
    route: '/KARSAAT/my-request/absent',
    requirePermit: [],
    requirePlugin: [],
    completelyDisable: false,
    lacksPermission: extractRequirePermits(KARSAATManagerItems),
    badgeKey: '',
  },
  {
    title: 'ماموریت',
    route: '/KARSAAT/my-request/mission',
    requirePermit: [],
    requirePlugin: [],
    completelyDisable: false,
    lacksPermission: extractRequirePermits(KARSAATManagerItems),
    badgeKey: '',
  },
  {
    title: 'تردد',
    route: '/KARSAAT/my-request/io',
    requirePermit: [],
    requirePlugin: [],
    completelyDisable: false,
    lacksPermission:extractRequirePermits(KARSAATManagerItems),
    badgeKey: '',
  },
  {
    title: 'شیفت',
    route: '/KARSAAT/my-request/shift',
    requirePermit:[],
    requirePlugin: [],
    completelyDisable: false,
    lacksPermission: extractRequirePermits(KARSAATManagerItems),
    badgeKey: '',
  },
  {
    title: 'حس و حال',
    route: '/KARSAAT/my-request/mood-condition',
    requirePermit: [],
    requirePlugin: [],
    completelyDisable: false,
    lacksPermission: extractRequirePermits(KARSAATManagerItems),
    badgeKey: '',
  },
]

export const headCategories = [
  {
    title: 'کارپوشه',
    subTitle: 'مدیریت همکارانی',
    icon: 'custom:KARPOOSHE',
    requireProduct: ['KARPOOSHE'],
    subGroup: 'KARPOOSHE',
  },
  {
    title: 'کارساعت',
    subTitle: 'حضور و غیاب آنلاین',
    icon: 'custom:KARSAAT',
    requireProduct: ['KARSAAT'],
    subGroup: 'KARSAAT',
  },
  {
    title: 'کارسال',
    subTitle: 'تقویم سازمانی آنلاین',
    icon: 'custom:KARSAAL',
    requireProduct: [],
    subGroup: 'KARSAAL',
  },
]
export const menuItems = {
  KARPOOSHE: [
    ...KARPOOSHEManagerItems,
    ...KARPOSHEEmployeeItems,
  ],
  KARSAAT: [
    {
      title: 'داشبورد',
      route: '/',
      requirePermit: [],
      requirePlugin: [],
      completelyDisable: false,
      lacksPermission: [],
      badgeKey: '',
    },
    ...KARSAATManagerItems,
    ...KARSAATEmployeeItems,
  ],
  KARSAAL: [
    {
      title: 'لیست تقویم',
      route: '/KARSAAL/calendars',
      requirePermit: [],
      requirePlugin: [],
      completelyDisable: false,
      lacksPermission: [],
      badgeKey: '',
    },
    {
      title: 'تخصیص تقویم',
      badgeKey: '',
      route: '/KARSAAL/assign-calendar',
      requirePermit: [],
      requirePlugin: [],
      completelyDisable: false,
      lacksPermission: [],
    },
    {
      title: 'تقویم سازمانی',
      badgeKey: '',
      route: '/KARSAAL/department-calendar',
      requirePermit: [],
      requirePlugin: [],
      completelyDisable: false,
      lacksPermission: [],
    },
    {
      title: 'راهنمای کارسال',
      badgeKey: '',
      route: '/KARSAAL/tutorial',
      requirePermit: [],
      requirePlugin: [],
      completelyDisable: false,
      lacksPermission: [],
    },
  ],
}

