export const dayTypes = {
  absent: {
    bg: 'tw-bg-[#0080FF]',
    bgLight: '!tw-bg-[#EBF5FF]',
    color: 'tw-text-[#0080FF]',
    hex: '#0080FF',
    title: 'مرخصی',
    text: 'مرخصی روزانه',
  },
  mission: {
    bg: 'tw-bg-[#4C49DA]',
    bgLight: '!tw-bg-[#EBEBFF]',
    color: 'tw-text-[#4C49DA]',
    hex: '#4C49DA',
    title: 'ماموریت',
    text: 'ماموریت روزانه',
  },
  inOut: {
    bg: 'tw-bg-[#ED4C67]',
    bgLight: '!tw-bg-[#FFEFE5]',
    color: 'tw-text-[#ED4C67]',
    hex: '#ED4C67',
    title: 'غیبت',
    text: 'غیبت',
  },
  holiday: {
    bg: 'tw-bg-[#F5F7FC]',
    bgLight: '!tw-bg-[#F5F7FC]',
    color: 'tw-text-[#EF866B]',
    hex: '#F5F7FC',
    title: 'تعطیلات رسمی',
    text: 'تعطیل رسمی',
  },
  inComplete: {
    bg: 'tw-bg-[#F68B1F]',
    bgLight: '!tw-bg-[#FFF2D4]',
    color: 'tw-text-[#F68B1F]',
    hex: '#F68B1F',
    title: 'تردد ناقص',
    text: 'تردد ناقص',
  },
  hasDescription: {
    bg: 'tw-bg-[#FFE500]',
    bgLight: '!tw-bg-white',
    color: 'tw-text-[#FFE500]',
    hex: '#FFE500',
    title: 'دارای توضیحات',
    text: '',
  },

  io: {
    bg: 'tw-bg-[#1ABC9C]',
    bgLight: '!tw-bg-[#1ABC9C33]',
    color: 'tw-text-[#1ABC9C]',
    hex: '#1ABC9C',
    title: 'تردد',
    text: '',
  },
}
