export const workReport = [
  {
    key: 'StandardWorkTime',
    icon: 'custom:clockWork',
    title: 'استاندارد دوره',
    isDayInfo: false,
    isClock: true,
    isHighlightable: false,

  },
  {
    key: 'NetWorkingDay',
    icon: 'custom:clockWork',
    title: 'روزهای کارکرد',
    isDayInfo: false,
    isClock: false,
    isHighlightable: false,
  },
  {
    key: 'TotalWorkTime',
    icon: 'custom:clockWork',
    title: 'ساعت کارکرد',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'Overtime',
    icon: 'custom:clockWork',
    title: 'اضافه کار',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'HolidayAndFriday',
    icon: 'custom:clockWork',
    title: 'تعطیل کاری و جمعه کاری',
    isDayInfo: false,
    isClock: true,
    isHighlightable: false,
  },
  {
    key: 'NightWorkTime',
    icon: 'custom:nightWork',
    title: 'شب کاری',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'ShortageTime',
    icon: 'custom:shortageTime',
    title: 'کسری کار',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'TotalVacation',
    icon: 'custom:vacation',
    title: 'مرخصی',
    isDayInfo: false,
    isClock: true,
    isHighlightable: false,
  },
  {
    key: 'OverTimeMax',
    icon: 'custom:clockWork',
    title: 'سقف اضافه کاری',
    isDayInfo: false,
    isClock: true,
    isHighlightable: false,
  },
  {
    key: 'PresentDayCount',
    icon: 'custom:clockWork',
    title: 'حضور شیفت',
    isDayInfo: false,
    isClock: false,
    isHighlightable: false,
  },
  {
    key: 'WorkTime',
    icon: 'custom:clockWork',
    title: 'کارکرد شیفت',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'OvertimeHoliday',
    icon: 'custom:overtimeHoliday',
    title: 'تعطیل کاری',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'OvertimeFriday',
    icon: 'custom:overtimeFriday',
    title: 'جمعه کاری',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'RushTime',
    icon: 'custom:rushTime',
    title: 'تعجیل',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'RotateWork1',
    icon: 'custom:rotateWork1',
    title: 'نوبت صبح عصر',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'RotateWork2',
    icon: 'custom:rotateWork2',
    title: 'نوبت صبح شب',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'RotateWork3',
    icon: 'custom:rotateWork3',
    title: 'نوبت عصر شب',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'MissionHourly',
    icon: 'custom:missionHourly',
    title: 'ماموریت ساعتی',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'MissionTime',
    icon: 'custom:mission',
    title: 'ماموریت روزانه',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'AbsentTime',
    icon: 'custom:absent',
    title: 'غیبت',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'DelayTime',
    icon: 'custom:delayTime',
    title: 'تأخیر',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'VacationHourly',
    icon: 'custom:vacationHourly',
    title: 'مرخصی ساعتی',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'Vacation',
    icon: 'custom:vacation',
    title: 'مرخصی روزانه',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
  {
    key: 'SickAbsentTime',
    icon: 'fa fa-user-md',
    title: 'مرخصی استعلاجی',
    isDayInfo: true,
    isClock: true,
    isHighlightable: true,
  },
]
