import { VBtn } from 'vuetify/components/VBtn'


export const aliases = {
  VBtnFilter : VBtn,
  VBtnAddItem : VBtn,
  VBtnTable : VBtn,
  VBtnCustom: VBtn,
  VBtnPrimary : VBtn,
  VBtnSuccess: VBtn,
  VBtnInfo: VBtn,
  VBtnError: VBtn,
  VBtnWarning: VBtn,
  VBtnCancel: VBtn,
  VBtnEdit: VBtn,
  VBTable: VBtn,
  VBtnRefresh : VBtn,
  VBtnSetting : VBtn,
  VBtnTableMobile : VBtn,
  VBtnConfirm : VBtn,
  VBtnBack : VBtn,
  VBtnTableTrash: VBtn,
  VBtnTableEdit:VBtn,
  VBtnTableSave:VBtn,
  VBtnTableHistory : VBtn,
  VBtnTableArchive: VBtn,
  VBtnTableCopy: VBtn,
  VBtnTableView: VBtn,
  VBtnCloseWindow:VBtn,
  VBtnExcel : VBtn,
  VBtnSearch : VBtn,
  VBtnTableConfirm:VBtn,
  VBtnTableInfo:VBtn,
}


export const defaults = {
  VBtnSuccess: {
    color: 'success',
    variant: 'flat',
    size: 'large',
    class: 'tw-mx-[4px] lg:tw-w-[180px] tw-w-[140px]',
    rounded: 'xl',
  },

  VBtnPrimary: {
    color: 'primary',
    variant: 'flat',
    size: 'large',
    class: 'tw-mx-[4px] lg:tw-w-[180px] tw-w-[140px]',
    rounded: 'xl',
  },
  VBtnInfo: {
    color: 'info',
    variant: 'flat',
    size: 'large',
    class: 'tw-mx-[4px] lg:tw-w-[180px] tw-w-[140px]',
    rounded: 'xl',
  },
  VBtnWarning: {
    color: 'warning',
    variant: 'flat',
    size: 'large',
    class: 'tw-mx-[4px] lg:tw-w-[180px] tw-w-[140px]',
    rounded: 'xl',
  },
  VBtnError: {
    color: 'error',
    variant: 'flat',
    size: 'large',
    class: 'tw-mx-[4px] lg:tw-w-[180px] tw-w-[140px]',
    rounded: 'xl',
  },
  VBtnCancel: {
    variant: 'outlined',
    size: 'large',
    class: 'tw-mx-[4px] lg:tw-w-[180px] tw-w-[120px]',
    rounded: 'xl',
  },

  VBtnEdit: {
    icon: 'custom:edit2',
    class: 'tw-bg-primary-500 !tw-text-white',
    size: 'x-small',
  },
  VBTable: {
    variant: 'outlined',
    rounded: 'lg',
    style: 'padding: 0;min-width: 10px',
    size: '30',
    class: 'tw-inline tw-m-2',
  },
  VBtnTable : {
    class:'vBtnTable tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'primary',
    style : { 'border-radius' : '10px!important' , 'font-size' : '13px' },
  },
  VBtnFilter : {
    color:"secondary",
    variant:"outlined",
    prependIcon:"custom:filter",
    size:"large",
    rounded:'xl',
    text:"فیلتر",
  },
  VBtnAddItem : {
    color:"secondary",
    size:"large",
    rounded:'xl',
    prependIcon:"custom:plusCircle",
    text:"افزودن آیتم جدید",
    elevation:'0',
  },
  VBtnRefresh : {
    variant: "text",
    icon: "mdi:mdi-refresh",
    size: "large",
    color : 'gray',
    class : 'tw-z-40 ',
  },
  VBtnSetting : {
    variant: "text",
    icon: "mdi:mdi-cog-outline",
    size: "large",
    color : 'gray',
    class : 'tw-z-40 ',
  },

  // this class is extracted from below btn  class:"inherit" becuase its change icon design to bold,
  VBtnTableMobile : {
    rounded:"lg",
    variant:"text",
    size:"small",
    plain : true,
  },
  VBtnConfirm : {
    color:"secondary",
    class:"tw-w-[120px] sm:tw-w-[180px]",
    size:"large",
    rounded:"xl",
  },
  VBtnBack : {
    color:"k_white-800",
    class:"tw-w-[120px]",
    variant:'tonal',
    size:"large",
    rounded:"xl",
  },

  VBtnTableTrash :{
    class : 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:'fa-regular fa-trash-can',
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px' },
  },

  VBtnTableEdit :{
    class : 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:'fa fa-pen',
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px' },
  },
  VBtnTableSave :{
    class : 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:'fas fa-save',
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px' },
  },

  VBtnTableHistory : {
    class : 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:'fa fa-history',
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px'  },
  },
  VBtnTableInfo : {
    class:'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:'fa fa-list',
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px'  },
  },
  VBtnTableArchive:{
    class: 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:'mdi:mdi-archive-outline',
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px'  },
  },
  VBtnTableCopy:{
    class: 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:"fas fa-copy",
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px'  },
  },
  VBtnTableConfirm:{
    class: 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'success',
    icon:"fa fa-check",
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px'  },
  },
  VBtnTableView:{
    class: 'tw-border-0 sm:tw-border',
    rounded:"lg",
    variant:"outlined",
    size:"x-small",
    color:'k_white-800',
    icon:"fa-regular fa-eye",
    style : { 'border-radius' : '10px!important' , 'font-size' : '10px'  },
  },
  VBtnCloseWindow:{
    icon:'fas fa-times',
    variant:'tonal',
    size:30,
    rounded:'lg',
    color:'primary',
    ripple: false,
  },
  VBtnExcel : {
    class: 'v-btn--excel',
    prependIcon : "mdi:mdi-microsoft-excel ",
    color : 'secondary',
    rounded : 'xl',
    size : 'large',
    variant :'outlined',
    elevation: 0,
    text : 'خروجی اکسل',
  },
  VBtnSearch : {
    class: 'v-btn--search',
    prependIcon : "fa fa-search",
    color : 'secondary',
    rounded : 'xl',
    size : 'large',
    variant : 'outlined',
    elevation: 0,
    text : 'جستجوی پیشرفته',
  },

}

